name: Build Merge For All Platforms (Xcode 16 & Xcode 15.4)
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        path: merge
    - name: Cache derived data
      if: ${{ !env.ACT }} # Skipping when run locally.
      uses: actions/cache@v3
      with:
        path: ~/Library/Developer/Xcode/DerivedData
        key: ${{ runner.os }}-derived-data
        restore-keys: |
          ${{ runner.os }}-derived-data
    - name: Run Preternatural Build (Xcode 16)
      uses: PreternaturalAI/github-action@main
      with:
        command: build
        derived_data_path: ~/Library/Developer/Xcode/DerivedData
        xcode-version: '16'
        build_all_platforms: 'true'
        working-directory: 'merge'
    - name: Run Preternatural Build (Xcode 15.4)
      uses: PreternaturalAI/github-action@main
      with:
        command: build
        derived_data_path: ~/Library/Developer/Xcode/DerivedData
        xcode-version: '15.4'
        build_all_platforms: 'true'
        working-directory: 'merge'