name: Preternatural Build
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ghcr.io/cirruslabs/macos-runner:sonoma
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Run Preternatural Build (Xcode 16)
      uses: PreternaturalAI/github-action/preternatural-build@main
      with:
        xcode-version: '16'
        configuration: 'debug'